export const FETCH_FAILED = "FETCH_FAILED";
export const SET_PERSONAGES = "SET_PERSONAGES";
export const LOADING_PERSONAGES = "LOADING_PERSONAGES";
export const SORT_PERSONAGES = "SORT_PERSONAGES";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";




